"use client";
/**
 * @author Randi Egan
 * @date   Aug/09/2024
 */


import React, {createContext, Dispatch, JSX, PropsWithChildren, SetStateAction, useState, useEffect} from "react";

// const pokemonHistorySessionStorage = null;// localStorage.getItem("pokemonHistory");
const pokemonHistorySessionStorage = JSON.stringify(["eevee",
    "magmar",
    "piplup",
    "snorlax",
    "munchlax",
    "sandshrew",
    "tentacool",
    "tentacruel",
    "poliwhirl",
    "poliwag",
    "horsea",
    "articuno",
    "moltres",
    "zapdos",
    "mew",
    "mewtwo",
    "pikachu",
    "pichu",
    "raichu",
    "gastly",
    "haunter",
    "gengar",
    "weedle",
    "kakuna",
    "beedrill",
    "caterpie",
    "metapod",
    "butterfree",
    "mr-mime",
    "jynx",
    "clefairy",
    "chansey",
    "jigglypuff",
    "wigglytuff",
    "hippopotas",
    "sandile",
    "starmie",
    "staryu",
    "golduck",
    "psyduck",
    "goldeen",
    "kingler",
    "krabby",
    "dragonite",
    "dratini",
    "dragonair",
    "charmander",
    "charmeleon",
    "charizard",
    "bulbasaur",
    "venusaur",
    "ivysaur",
    "squirtle",
    "wartortle",
    "blastoise",
    "meowth",
    "persian",
    "jolteon",
    "flareon",
    "vaporeon",
    "glaceon",
    "umbreon",
    "espeon",
    "leafeon",
    "sylveon",
    "rapidash",
    "ponyta",
    "magikarp",
    "gyarados",
    "lapras",
    "growlithe",
    "arcanine",
    "koffing",
    "weezing",
    "arbok",
    "ekans",
    "cubone",
    "marowak",
    "voltorb",
    "electrode",
    "muk",
    "grimer",
    "zubat",
    "golbat",
    "diglett",
    "dugtrio",
    "onix",
    "geodude",
    "graveler",
    "seadra",
    "seaking",
    "kingdra",
    "abra",
    "kadabra",
    "alakazam",
    "electabuzz",
    "scyther",
    "magnemite",
    "tangela",
    "cloyster",
    "rattata",
"weepinbell",
"bellsprout",
"primeape",
"machamp",
"machop",
"machoke",
"aerodactyl",
"doduo",
"dodrio",
"sandslash",
"seel",
"slowpoke",
"slowbro",
"paras",
"parasect",
"lickitung","raticate"])
// localStorage.setItem("pokemonHistory", pokemonHistorySessionStorage);

const defaultState = {
    pokemonHistory: pokemonHistorySessionStorage === null ? [] : JSON.parse(pokemonHistorySessionStorage),
};

interface IPokemonState {
    pokemonHistory: string[];
    setPokemonHistory: Dispatch<SetStateAction<string[]>>;
}

export const PokemonStateContext = createContext<IPokemonState>({} as IPokemonState);


export const PokemonStateProvider: React.FC<JSX.Element> = ({children}: PropsWithChildren<React.ReactNode>) => {
    const [pokemonHistory, setPokemonHistory] = useState<string[]>(defaultState.pokemonHistory);


    useEffect(() => {
        console.log("CONTEXT EFFECT");
        const defaultPokemon = [
            "eevee",
            "magmar",
            "piplup",
            "snorlax",
            "munchlax",
            "sandshrew",
            "tentacool",
            "tentacruel",
            "poliwhirl",
            "poliwag",
            "horsea",
            "articuno",
            "moltres",
            "zapdos",
            "mew",
            "mewtwo",
            "pikachu",
            "pichu",
            "raichu",
            "gastly",
            "haunter",
            "gengar",
            "weedle",
            "kakuna",
            "beedrill",
            "caterpie",
            "metapod",
            "butterfree",
            "mr-mime",
            "jynx",
            "clefairy",
            "chansey",
            "jigglypuff",
            "wigglytuff",
            "hippopotas",
            "sandile",
            "starmie",
            "staryu",
            "golduck",
            "psyduck",
            "goldeen",
            "kingler",
            "krabby",
            "dragonite",
            "dratini",
            "dragonair",
            "charmander",
            "charmeleon",
            "charizard",
            "bulbasaur",
            "venusaur",
            "ivysaur",
            "squirtle",
            "wartortle",
            "blastoise",
            "meowth",
            "persian",
            "jolteon",
            "flareon",
            "vaporeon",
            "glaceon",
            "umbreon",
            "espeon",
            "leafeon",
            "sylveon",
            "rapidash",
            "ponyta",
            "magikarp",
            "gyarados",
            "lapras",
            "growlithe",
            "arcanine",
            "koffing",
            "weezing",
            "arbok",
            "ekans",
            "cubone",
            "marowak",
            "voltorb",
            "electrode",
            "muk",
            "grimer",
            "zubat",
            "golbat",
            "diglett",
            "dugtrio",
            "onix",
            "geodude",
            "graveler",
            "seadra",
            "seaking",
            "kingdra",
            "abra",
            "kadabra",
            "alakazam",
            "electabuzz",
            "scyther",
            "magnemite",
            "tangela",
            "cloyster",
            "rattata",
            "weepinbell",
            "bellsprout",
            "primeape",
            "machamp",
            "machop",
            "machoke",
            "aerodactyl",
            "doduo",
            "dodrio",
            "sandslash",
            "seel",
            "slowpoke",
            "slowbro",
            "paras",
            "parasect",
            "lickitung"
        ]
        const pokemonHistorySessionStorage = localStorage.getItem("pokemonHistory");
        // pokemonHistory.push(...defaultPokemon);
        // console.log({pokemonHistory});

        setPokemonHistory(() =>{
            return defaultPokemon;
        });
    }, []);


    return (
        <PokemonStateContext.Provider
            value={{
                pokemonHistory,
                setPokemonHistory
            }}
        >
            {children}
        </PokemonStateContext.Provider>
    );
};
